### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by Human** [snipsco/snips-platform-android-demo#2]
The README doesn't indicate what has to be done in order to get a working demo.

I built and installed the APK, but logcat errors indicated that some files were missing. The directory in question (/storage/emulated/0/snips_android_assistant/) can be created manually in an adb shell session, and most of the files are inside the assistant_proj*.zip file that can be downloaded from your site, and I copied them over. However, even after placing these inside snips_android_assistant, there's a remaining detail-lacking error about missing files in /storage/emulated/0/snips_android_assistant/custom_asr

**Comment by klefevre** [comment]
Because the android version of the platform is in a very alpha state, we didn't took the time to write a decent documentation but it definitively deserves some love. However you could find some help [here](https://github.com/snipsco/snips-platform-documentation/wiki/2.-Create-an-assistant-using-an-existing-bundle#step-3b-install-the-assistant-on-android ).

From what you said I think you have an old assistant that you need to retrain on the console. But there will still have a manual step to do which is adding the directory `custom_dialogue`(downloadable [here](https://github.com/snipsco/snips-platform-documentation/wiki/resources/custom_dialogue.zip) ) in your assistant folder.

**Comment by shanness** [comment]
Bummer the above wiki link is now 404ing..  Would be great if you had instructions of how to get the zip onto an android device.

Unfortunately the wayback engine has only indexed the root of the wiki, not that page :(

https://web.archive.org/web/20180503003710/https://github.com/snipsco/snips-platform-documentation/wiki

**Comment by shanness** [comment]
For anyone else that ends up here, I had to download the zip from the console, unzip it and run these commands.
```
mv assistant snips_android_assistant
adb push snips_android_assistant /storage/emulated/0/
```

The hotword defaults to `hey snips`  And it's working, nice.  Thanks guys, look forward to playing with this.

**Comment by fredszaq** [comment]
hi @shanness he info was on the readme but the commands were not explicit, I've added them.

The documentation now lives [here
](https://snips.gitbook.io/documentation/installing-snips/on-android)
